### ISSUE TITLE
Listening to-Status

### ISSUE THREAD

**Issue by wechselgeld** [sleequid/tidalRPC#11]
Hey! Since Vencord or other client mods provide activity types like `Listening to [Activity]`, I was wondering if it would be possible to implement this in the RPC as well? I would do it myself, but I have zero knowledge of the Discord.js RPC extension.

**Comment by TheKfcBandit** [comment]
these activities aren't accessible via RPC server and require direct access to your discord account via the API. unfortunately this falls under the umbrella of account automation (self botting) and comes with the risk of getting your account terminated as well as the vulnerability of having to expose your token to the application.

**Comment by rxri** [comment]
I had PoC for it, but that requires connecting to websocket directly and your token which unfortunately isn't ideal. RPC allows only one activity type - Playing. Sticking to modifying it in Vencord or any other client is the safest option. As long as you will not abuse it, you should be fine.

**Comment by TheKfcBandit** [comment]
I know this is a bit off-topic now, but I wouldn't recommend even using such a thing. These sorts of statuses are notorious with user bots. Because of this, being in any reasonably large server will likely draw attention to you, and you will likely face numerous reports, and the chances of your account being terminated are not insignificant.

**Comment by rxri** [comment]
I'm not going to question their motivation. It's their own personal choice if they want to break ToS and risk getting banned
